
package sistram4.web;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SistramAis3", targetNamespace = "http://web.sistram4/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SistramAis3 {


    /**
     * 
     * @return
     *     returns java.util.List<sistram4.web.Navio>
     */
    @WebMethod(operationName = "GetShipList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetShipList", targetNamespace = "http://web.sistram4/", className = "sistram4.web.GetShipList")
    @ResponseWrapper(localName = "GetShipListResponse", targetNamespace = "http://web.sistram4/", className = "sistram4.web.GetShipListResponse")
    @Action(input = "http://web.sistram4/SistramAis3/GetShipListRequest", output = "http://web.sistram4/SistramAis3/GetShipListResponse")
    public List<Navio> getShipList();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<sistram4.web.Navio>
     */
    @WebMethod(operationName = "GetShipListData")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetShipListData", targetNamespace = "http://web.sistram4/", className = "sistram4.web.GetShipListData")
    @ResponseWrapper(localName = "GetShipListDataResponse", targetNamespace = "http://web.sistram4/", className = "sistram4.web.GetShipListDataResponse")
    @Action(input = "http://web.sistram4/SistramAis3/GetShipListDataRequest", output = "http://web.sistram4/SistramAis3/GetShipListDataResponse")
    public List<Navio> getShipListData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
