
package sistram4.web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SistramAis3Service", targetNamespace = "http://web.sistram4/", wsdlLocation = "http://www.sistram.mar.mil.br:8082//Sistram4SEExt/SistramAis3Service?wsdl")
public class SistramAis3Service
    extends Service
{

    private final static URL SISTRAMAIS3SERVICE_WSDL_LOCATION;
    private final static WebServiceException SISTRAMAIS3SERVICE_EXCEPTION;
    private final static QName SISTRAMAIS3SERVICE_QNAME = new QName("http://web.sistram4/", "SistramAis3Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.sistram.mar.mil.br:8082//Sistram4SEExt/SistramAis3Service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SISTRAMAIS3SERVICE_WSDL_LOCATION = url;
        SISTRAMAIS3SERVICE_EXCEPTION = e;
    }

    public SistramAis3Service() {
        super(__getWsdlLocation(), SISTRAMAIS3SERVICE_QNAME);
    }

    public SistramAis3Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SISTRAMAIS3SERVICE_QNAME, features);
    }

    public SistramAis3Service(URL wsdlLocation) {
        super(wsdlLocation, SISTRAMAIS3SERVICE_QNAME);
    }

    public SistramAis3Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SISTRAMAIS3SERVICE_QNAME, features);
    }

    public SistramAis3Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SistramAis3Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SistramAis3
     */
    @WebEndpoint(name = "SistramAis3Port")
    public SistramAis3 getSistramAis3Port() {
        return super.getPort(new QName("http://web.sistram4/", "SistramAis3Port"), SistramAis3.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SistramAis3
     */
    @WebEndpoint(name = "SistramAis3Port")
    public SistramAis3 getSistramAis3Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://web.sistram4/", "SistramAis3Port"), SistramAis3.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SISTRAMAIS3SERVICE_EXCEPTION!= null) {
            throw SISTRAMAIS3SERVICE_EXCEPTION;
        }
        return SISTRAMAIS3SERVICE_WSDL_LOCATION;
    }

}
